# Generated by Django 5.0.3 on 2024-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinhnut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('b', models.FloatField()),
                ('h', models.FloatField()),
                ('L', models.FloatField()),
                ('cben', models.CharField()),
                ('nthep', models.CharField()),
                ('thepd', models.CharField()),
                ('a', models.FloatField()),
                ('thept', models.CharField()),
                ('a1', models.FloatField()),
            ],
        ),
    ]
